Repository Unity-Technologies/com.unity.multiplayer.rfcs, pull requests merged in 2021-08, with the labels that each got.

#27 Rfc/snapshot system
  text/0000-snapshot-system.md
  text/0000-snapshot-system/snapshot.exchange.rfc.png
  text/0000-snapshot-system/snapshot.message.rfc.png
  text/0000-snapshot-system/snapshot.rfc.png
Labels: final-comment-period

#18 Message Ordering Guarantee
  text/0018-message-ordering-guarantee.md
Labels: open

#26 Serialization RFC
  text/0026-serialization.md
Labels: open

#28 NetworkTransform Interpolation
  text/0028-network-transform-buffered-interpolation.md
  text/0028-network-transform-buffered-interpolation/InterpolatorConfiguration.png
  text/0028-network-transform-buffered-interpolation/InterpolatorConfigurationSO.png
  text/0028-network-transform-buffered-interpolation/jitter.jpg
  text/0028-network-transform-buffered-interpolation/jitter_with_buffer.jpg
Labels: open, final-comment-period
